package edu.pitt.sis.infsci2711.multidbs.vis.dal.orm;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ColfusionCanvases generated by hbm2java
 */
public class ColfusionCanvases implements java.io.Serializable {

	private Integer vid;
	private ColfusionUsers colfusionUsers;
	private String name;
	private String note;
	private Date mdate;
	private Date cdate;
	private Integer privilege;
	private Set colfusionShareses = new HashSet(0);
	private Set colfusionChartses = new HashSet(0);

	public ColfusionCanvases() {
	}

	public ColfusionCanvases(Date mdate, Date cdate) {
		this.mdate = mdate;
		this.cdate = cdate;
	}

	public ColfusionCanvases(ColfusionUsers colfusionUsers, String name,
			String note, Date mdate, Date cdate, Integer privilege,
			Set colfusionShareses, Set colfusionChartses) {
		this.colfusionUsers = colfusionUsers;
		this.name = name;
		this.note = note;
		this.mdate = mdate;
		this.cdate = cdate;
		this.privilege = privilege;
		this.colfusionShareses = colfusionShareses;
		this.colfusionChartses = colfusionChartses;
	}

	public Integer getVid() {
		return this.vid;
	}

	public void setVid(Integer vid) {
		this.vid = vid;
	}

	public ColfusionUsers getColfusionUsers() {
		return this.colfusionUsers;
	}

	public void setColfusionUsers(ColfusionUsers colfusionUsers) {
		this.colfusionUsers = colfusionUsers;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getMdate() {
		return this.mdate;
	}

	public void setMdate(Date mdate) {
		this.mdate = mdate;
	}

	public Date getCdate() {
		return this.cdate;
	}

	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	public Integer getPrivilege() {
		return this.privilege;
	}

	public void setPrivilege(Integer privilege) {
		this.privilege = privilege;
	}

	public Set getColfusionShareses() {
		return this.colfusionShareses;
	}

	public void setColfusionShareses(Set colfusionShareses) {
		this.colfusionShareses = colfusionShareses;
	}

	public Set getColfusionChartses() {
		return this.colfusionChartses;
	}

	public void setColfusionChartses(Set colfusionChartses) {
		this.colfusionChartses = colfusionChartses;
	}

}

